on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: Setup .NET Core
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build
    - name: Publish win10-x64
      run: dotnet publish --configuration Release --runtime win10-x64 --output ./output/publish/win10-x64 ./src/KubernetesDotnetDiagnostics/KubernetesDotnetDiagnostics.csproj /p:PublishProfile=Properties/PublishProfiles/FolderProfile.pubxml
    - name: Publish linux-x64
      run: dotnet publish --configuration Release --runtime linux-x64 --output ./output/publish/linux-x64 ./src/KubernetesDotnetDiagnostics/KubernetesDotnetDiagnostics.csproj /p:PublishProfile=Properties/PublishProfiles/FolderProfile.pubxml
    - name: Publish osx-x64
      run: dotnet publish --configuration Release --runtime osx-x64   --output ./output/publish/osx-x64 ./src/KubernetesDotnetDiagnostics/KubernetesDotnetDiagnostics.csproj /p:PublishProfile=Properties/PublishProfiles/FolderProfile.pubxml
    - uses: actions/upload-artifact@v2
      with:
        name: publish
        path: output/publish/